-- DPM_CUSTOMER_360.GOLD - unified customer 360 view, built from
-- DPM_SRC_CRM.SILVER.CUSTOMERS + DPM_SRC_BILLING.SILVER.INVOICES.
-- Cross-database task predecessors (AFTER) aren't supported on this account,
-- so this task runs independently on its own schedule and only acts when a
-- relevant silver stream has data.

CREATE SCHEMA IF NOT EXISTS DPM_CUSTOMER_360.GOLD;

CREATE TABLE IF NOT EXISTS DPM_CUSTOMER_360.GOLD.CUSTOMER_360 (
  CUSTOMER_ID NUMBER,
  FULL_NAME STRING,
  EMAIL STRING,
  SIGNUP_DATE DATE,
  TOTAL_INVOICES NUMBER,
  TOTAL_AMOUNT NUMBER(14,2),
  LAST_INVOICE_DATE DATE,
  UPDATED_AT TIMESTAMP_NTZ
) COMMENT = 'Gold: unified customer 360 view (CRM + Billing)';

CREATE OR REPLACE TASK DPM_CUSTOMER_360.GOLD.TASK_SILVER_TO_GOLD_CUSTOMER_360
  WAREHOUSE = DPM_PIPELINE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('DPM_SRC_CRM.SILVER.CUSTOMERS_STREAM') OR SYSTEM$STREAM_HAS_DATA('DPM_SRC_BILLING.SILVER.INVOICES_STREAM')
AS
MERGE INTO DPM_CUSTOMER_360.GOLD.CUSTOMER_360 tgt
USING (
  WITH changed_ids AS (
    SELECT CUSTOMER_ID FROM DPM_SRC_CRM.SILVER.CUSTOMERS_STREAM
    UNION
    SELECT CUSTOMER_ID FROM DPM_SRC_BILLING.SILVER.INVOICES_STREAM
  )
  SELECT
    c.CUSTOMER_ID,
    c.FULL_NAME,
    c.EMAIL,
    c.SIGNUP_DATE,
    COUNT(i.INVOICE_ID) AS TOTAL_INVOICES,
    COALESCE(SUM(i.AMOUNT), 0) AS TOTAL_AMOUNT,
    MAX(i.INVOICE_DATE) AS LAST_INVOICE_DATE
  FROM DPM_SRC_CRM.SILVER.CUSTOMERS c
  LEFT JOIN DPM_SRC_BILLING.SILVER.INVOICES i ON i.CUSTOMER_ID = c.CUSTOMER_ID
  WHERE c.CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM changed_ids)
  GROUP BY c.CUSTOMER_ID, c.FULL_NAME, c.EMAIL, c.SIGNUP_DATE
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
  FULL_NAME = src.FULL_NAME, EMAIL = src.EMAIL, SIGNUP_DATE = src.SIGNUP_DATE,
  TOTAL_INVOICES = src.TOTAL_INVOICES, TOTAL_AMOUNT = src.TOTAL_AMOUNT, LAST_INVOICE_DATE = src.LAST_INVOICE_DATE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, FULL_NAME, EMAIL, SIGNUP_DATE, TOTAL_INVOICES, TOTAL_AMOUNT, LAST_INVOICE_DATE, UPDATED_AT)
  VALUES (src.CUSTOMER_ID, src.FULL_NAME, src.EMAIL, src.SIGNUP_DATE, src.TOTAL_INVOICES, src.TOTAL_AMOUNT, src.LAST_INVOICE_DATE, CURRENT_TIMESTAMP());

CREATE OR REPLACE PROCEDURE DPM_CUSTOMER_360.GOLD.SP_GENERATE_DUMMY_DATA(NUM_CUSTOMERS INTEGER, NUM_INVOICES_PER_CUSTOMER INTEGER)
RETURNS STRING
LANGUAGE SQL
COMMENT = 'Inserts dummy rows into bronze tables (CRM customers + billing invoices) to trigger the bronze -> silver -> gold pipeline'
AS
$$
DECLARE
  i INTEGER DEFAULT 0;
  j INTEGER DEFAULT 0;
  new_cust_id INTEGER;
  total_invoices INTEGER DEFAULT 0;
BEGIN
  WHILE (i < NUM_CUSTOMERS) DO
    SELECT DPM_SRC_CRM.BRONZE.SEQ_CUSTOMER_ID.NEXTVAL INTO :new_cust_id;

    INSERT INTO DPM_SRC_CRM.BRONZE.CUSTOMERS_RAW (RAW_PAYLOAD)
    SELECT OBJECT_CONSTRUCT(
      'customer_id', :new_cust_id,
      'full_name', 'Customer ' || :new_cust_id,
      'email', 'customer' || :new_cust_id || '@example.com',
      'signup_date', TO_VARCHAR(DATEADD(day, -UNIFORM(1, 365, RANDOM()), CURRENT_DATE()))
    );

    j := 0;
    WHILE (j < NUM_INVOICES_PER_CUSTOMER) DO
      INSERT INTO DPM_SRC_BILLING.BRONZE.INVOICES_RAW (RAW_PAYLOAD)
      SELECT OBJECT_CONSTRUCT(
        'invoice_id', DPM_SRC_BILLING.BRONZE.SEQ_INVOICE_ID.NEXTVAL,
        'customer_id', :new_cust_id,
        'amount', ROUND(UNIFORM(10, 1000, RANDOM()) + UNIFORM(0, 99, RANDOM()) / 100.0, 2),
        'status', ARRAY_CONSTRUCT('PAID', 'PENDING', 'OVERDUE')[UNIFORM(0, 2, RANDOM())],
        'invoice_date', TO_VARCHAR(DATEADD(day, -UNIFORM(0, 90, RANDOM()), CURRENT_DATE()))
      );
      j := j + 1;
      total_invoices := total_invoices + 1;
    END WHILE;

    i := i + 1;
  END WHILE;

  RETURN 'Inserted ' || NUM_CUSTOMERS || ' customer(s) into DPM_SRC_CRM.BRONZE.CUSTOMERS_RAW and ' || total_invoices || ' invoice(s) into DPM_SRC_BILLING.BRONZE.INVOICES_RAW. Pipeline tasks (1-minute schedule) will propagate them to SILVER then GOLD.';
END;
$$;

CREATE OR REPLACE TASK DPM_CUSTOMER_360.GOLD.TASK_GENERATE_DUMMY_DATA
  WAREHOUSE = DPM_PIPELINE_WH
  SCHEDULE = '60 MINUTE'
  COMMENT = 'Hourly generator of dummy bronze data to keep the bronze->silver->gold test pipeline exercised'
AS
CALL DPM_CUSTOMER_360.GOLD.SP_GENERATE_DUMMY_DATA(3, 2);
