-- DPM_SRC_INVENTORY.BRONZE - raw landing layer for product/inventory snapshots.

CREATE SCHEMA IF NOT EXISTS DPM_SRC_INVENTORY.BRONZE;

CREATE SEQUENCE IF NOT EXISTS DPM_SRC_INVENTORY.BRONZE.SEQ_PRODUCT_ID START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS DPM_SRC_INVENTORY.BRONZE.PRODUCTS_RAW (
  RECORD_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  RAW_PAYLOAD VARIANT,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Bronze: raw landed product/inventory snapshot records (append-only)';

CREATE STREAM IF NOT EXISTS DPM_SRC_INVENTORY.BRONZE.PRODUCTS_RAW_STREAM
  ON TABLE DPM_SRC_INVENTORY.BRONZE.PRODUCTS_RAW
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new rows landed in bronze products';

CREATE OR REPLACE TASK DPM_SRC_INVENTORY.BRONZE.TASK_BRONZE_TO_SILVER_PRODUCTS
  WAREHOUSE = DPM_PIPELINE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('DPM_SRC_INVENTORY.BRONZE.PRODUCTS_RAW_STREAM')
AS
MERGE INTO DPM_SRC_INVENTORY.SILVER.PRODUCTS tgt
USING (
  SELECT
    RAW_PAYLOAD:product_id::NUMBER AS PRODUCT_ID,
    RAW_PAYLOAD:product_name::STRING AS PRODUCT_NAME,
    RAW_PAYLOAD:category::STRING AS CATEGORY,
    RAW_PAYLOAD:unit_price::NUMBER(10,2) AS UNIT_PRICE,
    RAW_PAYLOAD:quantity_on_hand::NUMBER AS QUANTITY_ON_HAND,
    -- BUG: the bronze payload key is "warehouse_id" (see
    -- SP_GENERATE_DUMMY_PRODUCTS in ../dpm_inventory_360/gold.sql), but this
    -- reads "warehouse" instead, so WAREHOUSE_ID lands NULL for every row.
    RAW_PAYLOAD:warehouse::STRING AS WAREHOUSE_ID
  FROM DPM_SRC_INVENTORY.BRONZE.PRODUCTS_RAW_STREAM
  WHERE METADATA$ACTION = 'INSERT'
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
  PRODUCT_NAME = src.PRODUCT_NAME, CATEGORY = src.CATEGORY, UNIT_PRICE = src.UNIT_PRICE,
  QUANTITY_ON_HAND = src.QUANTITY_ON_HAND, WAREHOUSE_ID = src.WAREHOUSE_ID, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE, QUANTITY_ON_HAND, WAREHOUSE_ID, UPDATED_AT)
  VALUES (src.PRODUCT_ID, src.PRODUCT_NAME, src.CATEGORY, src.UNIT_PRICE, src.QUANTITY_ON_HAND, src.WAREHOUSE_ID, CURRENT_TIMESTAMP());
