-- DPM_INVENTORY_360.GOLD - per-product stock summary, built from
-- DPM_SRC_INVENTORY.SILVER.PRODUCTS.

CREATE SCHEMA IF NOT EXISTS DPM_INVENTORY_360.GOLD;

CREATE TABLE IF NOT EXISTS DPM_INVENTORY_360.GOLD.PRODUCT_STOCK_SUMMARY (
  PRODUCT_ID NUMBER,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  WAREHOUSE_ID STRING,
  QUANTITY_ON_HAND NUMBER,
  UNIT_PRICE NUMBER(10,2),
  TOTAL_VALUE NUMBER(14,2),
  UPDATED_AT TIMESTAMP_NTZ
) COMMENT = 'Gold: per-product stock summary with computed inventory value';

CREATE OR REPLACE TASK DPM_INVENTORY_360.GOLD.TASK_SILVER_TO_GOLD_PRODUCT_STOCK
  WAREHOUSE = DPM_PIPELINE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('DPM_SRC_INVENTORY.SILVER.PRODUCTS_STREAM')
AS
MERGE INTO DPM_INVENTORY_360.GOLD.PRODUCT_STOCK_SUMMARY tgt
USING (
  WITH changed_ids AS (
    SELECT PRODUCT_ID FROM DPM_SRC_INVENTORY.SILVER.PRODUCTS_STREAM
  )
  SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.WAREHOUSE_ID,
    p.QUANTITY_ON_HAND,
    p.UNIT_PRICE,
    p.QUANTITY_ON_HAND * p.UNIT_PRICE AS TOTAL_VALUE
  FROM DPM_SRC_INVENTORY.SILVER.PRODUCTS p
  WHERE p.PRODUCT_ID IN (SELECT PRODUCT_ID FROM changed_ids)
    -- BUG: this was meant to be a "hide zero-stock from a low-stock alert
    -- view" filter that got copy-pasted into the main gold merge instead.
    -- It silently drops every out-of-stock product from gold entirely, so
    -- GOLD.PRODUCT_STOCK_SUMMARY row count < SILVER.PRODUCTS row count.
    AND p.QUANTITY_ON_HAND > 0
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
  PRODUCT_NAME = src.PRODUCT_NAME, CATEGORY = src.CATEGORY, WAREHOUSE_ID = src.WAREHOUSE_ID,
  QUANTITY_ON_HAND = src.QUANTITY_ON_HAND, UNIT_PRICE = src.UNIT_PRICE, TOTAL_VALUE = src.TOTAL_VALUE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, WAREHOUSE_ID, QUANTITY_ON_HAND, UNIT_PRICE, TOTAL_VALUE, UPDATED_AT)
  VALUES (src.PRODUCT_ID, src.PRODUCT_NAME, src.CATEGORY, src.WAREHOUSE_ID, src.QUANTITY_ON_HAND, src.UNIT_PRICE, src.TOTAL_VALUE, CURRENT_TIMESTAMP());

CREATE OR REPLACE PROCEDURE DPM_INVENTORY_360.GOLD.SP_GENERATE_DUMMY_PRODUCTS(NUM_PRODUCTS INTEGER)
RETURNS STRING
LANGUAGE SQL
COMMENT = 'Inserts dummy product rows into bronze (some out-of-stock) to trigger the bronze -> silver -> gold inventory pipeline'
AS
$$
DECLARE
  i INTEGER DEFAULT 0;
  new_product_id INTEGER;
BEGIN
  WHILE (i < NUM_PRODUCTS) DO
    SELECT DPM_SRC_INVENTORY.BRONZE.SEQ_PRODUCT_ID.NEXTVAL INTO :new_product_id;

    INSERT INTO DPM_SRC_INVENTORY.BRONZE.PRODUCTS_RAW (RAW_PAYLOAD)
    SELECT OBJECT_CONSTRUCT(
      'product_id', :new_product_id,
      'product_name', 'Product ' || :new_product_id,
      'category', ARRAY_CONSTRUCT('ELECTRONICS', 'GROCERY', 'APPAREL', 'HOME')[UNIFORM(0, 3, RANDOM())],
      'unit_price', ROUND(UNIFORM(5, 500, RANDOM()) + UNIFORM(0, 99, RANDOM()) / 100.0, 2),
      -- ~30% of products are out of stock, to exercise the gold filter bug
      'quantity_on_hand', CASE WHEN UNIFORM(0, 9, RANDOM()) < 3 THEN 0 ELSE UNIFORM(1, 200, RANDOM()) END,
      'warehouse_id', 'WH-' || UNIFORM(1, 5, RANDOM())
    );

    i := i + 1;
  END WHILE;

  RETURN 'Inserted ' || NUM_PRODUCTS || ' product(s) into DPM_SRC_INVENTORY.BRONZE.PRODUCTS_RAW.';
END;
$$;

CREATE OR REPLACE TASK DPM_INVENTORY_360.GOLD.TASK_GENERATE_DUMMY_PRODUCTS
  WAREHOUSE = DPM_PIPELINE_WH
  SCHEDULE = '60 MINUTE'
  COMMENT = 'Hourly generator of dummy product data to keep the inventory bronze->silver->gold test pipeline exercised'
AS
CALL DPM_INVENTORY_360.GOLD.SP_GENERATE_DUMMY_PRODUCTS(10);
