"""Add check revisions

Revision ID: 7b88e26d6458
Revises: e5de477a9576
Create Date: 2026-09-21 19:04:59.096181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b88e26d6458'
down_revision: Union[str, Sequence[str], None] = 'e5de477a9576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('check_id', sa.String(), nullable=True),
    sa.Column('database_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposed_name', sa.String(), nullable=True),
    sa.Column('proposed_type', sa.String(), nullable=True),
    sa.Column('proposed_schedule', sa.String(), nullable=True),
    sa.Column('proposed_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_change', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by_commit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_revisions_check_id'), 'check_revisions', ['check_id'], unique=False)
    op.create_index(op.f('ix_check_revisions_database_id'), 'check_revisions', ['database_id'], unique=False)
    op.create_index(op.f('ix_check_revisions_status'), 'check_revisions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_revisions_status'), table_name='check_revisions')
    op.drop_index(op.f('ix_check_revisions_database_id'), table_name='check_revisions')
    op.drop_index(op.f('ix_check_revisions_check_id'), table_name='check_revisions')
    op.drop_table('check_revisions')
    # ### end Alembic commands ###
