"""add repo provenance to projects and databases

Revision ID: 7ea816a49699
Revises: 7e4b0c92aa15
Create Date: 2026-09-17 22:59:56.954285

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ea816a49699'
down_revision: Union[str, Sequence[str], None] = '7e4b0c92aa15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The map that rca/object_repo_map.py hardcoded before repo paths became
# per-database. Backfilling from it keeps RCA's git attribution working for
# projects that already exist - without this, every seeded database silently
# loses the file mapping the moment the static map is deleted, and RCA starts
# answering "not tracked in git" for objects that are.
LEGACY_OBJECT_PATHS = {
    "DPM_SRC_CRM": {"BRONZE": "snowflake/dpm_src_crm/bronze.sql", "SILVER": "snowflake/dpm_src_crm/silver.sql"},
    "DPM_SRC_BILLING": {"BRONZE": "snowflake/dpm_src_billing/bronze.sql", "SILVER": "snowflake/dpm_src_billing/silver.sql"},
    "DPM_SRC_INVENTORY": {"BRONZE": "snowflake/dpm_src_inventory/bronze.sql", "SILVER": "snowflake/dpm_src_inventory/silver.sql"},
    "DPM_CUSTOMER_360": {"GOLD": "snowflake/dpm_customer_360/gold.sql"},
    "DPM_INVENTORY_360": {"GOLD": "snowflake/dpm_inventory_360/gold.sql"},
}


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('databases', sa.Column('repo_paths', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('projects', sa.Column('repo_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('repo_ref', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('repo_commit', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('repo_path', sa.String(), nullable=True))

    # projects.repo_path is deliberately left null here rather than filled with
    # this machine's checkout directory: a path baked into a migration is wrong
    # on every other machine. git_context falls back to the app's own repo root
    # when it is null, which is exactly the pre-migration behaviour.
    connection = op.get_bind()
    for database_name, repo_paths in LEGACY_OBJECT_PATHS.items():
        connection.execute(
            sa.text("UPDATE databases SET repo_paths = :paths WHERE name = :name"),
            {"paths": json.dumps(repo_paths), "name": database_name},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'repo_path')
    op.drop_column('projects', 'repo_commit')
    op.drop_column('projects', 'repo_ref')
    op.drop_column('projects', 'repo_url')
    op.drop_column('databases', 'repo_paths')
    # ### end Alembic commands ###
