"""Move tickets to Jira only

Tickets are no longer a thing this app owns. An incident is the record of
what went wrong and what was said about it; the Jira issue is the external
face of that incident, and it lives in Jira. This app holds a reference and
a cached view of the issue's status, refreshed once per monitor sweep,
because "has anyone responded to this" is a question only Jira can answer
and escalation depends on it.

The `tickets` table is dropped. Rows that were real Jira issues (those with
an `external_key`) are salvaged onto their incident first; in-app board
tickets are not, because their keys mean nothing outside this database.

With Jira unconfigured there is now no tracker at all - incidents are still
opened, escalated and cleared here, they simply have no issue attached.

Revision ID: bf05f779ddae
Revises: 7b88e26d6458
Create Date: 2026-09-21 22:13:08.938976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf05f779ddae'
down_revision: Union[str, Sequence[str], None] = '7b88e26d6458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The reference first, so the drop below has somewhere to salvage into.
    op.add_column('incidents', sa.Column('ticket_key', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('ticket_url', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('ticket_status', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('ticket_assignee', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('ticket_synced_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('ticket_moved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_incidents_ticket_key'), 'incidents', ['ticket_key'], unique=False)

    # Salvage the tickets that were real Jira issues. Only rows with an
    # `external_key` ever existed outside this app; the rest were in-app board
    # tickets whose identity (`DPM-382`) means nothing to Jira, and carrying
    # those keys over would produce incidents that appear to reference issues
    # nobody can open.
    #
    # Nothing is lost by dropping them. Every board ticket's substance -
    # title, severity, when it opened, what happened on it - is already on the
    # incident it belonged to and in that incident's event stream. The ticket
    # row was the external face, and the external face is Jira's job now.
    op.execute(
        sa.text(
            """
            UPDATE incidents i
            SET ticket_key      = t.external_key,
                ticket_url      = t.external_url,
                ticket_status   = t.status,
                ticket_assignee = t.assignee,
                ticket_moved_at = t.updated_at
            FROM tickets t
            WHERE t.incident_id = i.id
              AND t.external_key IS NOT NULL
            """
        )
    )
    op.drop_table('tickets')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_ticket_key'), table_name='incidents')
    op.drop_column('incidents', 'ticket_moved_at')
    op.drop_column('incidents', 'ticket_synced_at')
    op.drop_column('incidents', 'ticket_assignee')
    op.drop_column('incidents', 'ticket_status')
    op.drop_column('incidents', 'ticket_url')
    op.drop_column('incidents', 'ticket_key')
    op.create_table('tickets',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('check_run_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['check_run_id'], ['check_runs.id'], name=op.f('fk_tickets_check_run_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_tickets_incident_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_pkey')),
    sa.UniqueConstraint('incident_id', name=op.f('uq_tickets_incident_id'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('key', name=op.f('tickets_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
