"""Add incidents and check provenance

An incident is the thing that fails, warns and clears; a run is evidence
about it. Tickets move from `check_run_id` to `incident_id` because a ticket
bound to one run cannot express "still failing" - which is the whole reason
every failed run used to file a fresh ticket.

Two backfills, both deriving from what is already there rather than guessing:

* Every existing ticket gets an incident synthesised from its run, so no
  ticket is orphaned when the UI starts reading incidents.
* Existing checks are marked `origin = HUMAN`. Their real provenance is
  unknowable after the fact, and HUMAN is the safe direction: it means the
  maintenance agent proposes rather than rewrites. Marking them DERIVED
  would hand the agent permission nobody granted it.

Revision ID: e5de477a9576
Revises: 7ea816a49699
Create Date: 2026-09-21 18:43:55.390994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5de477a9576'
down_revision: Union[str, Sequence[str], None] = '7ea816a49699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('check_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('first_run_id', sa.String(), nullable=True),
    sa.Column('last_run_id', sa.String(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_passes', sa.Integer(), nullable=False),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('last_escalated_at', sa.DateTime(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('triage_source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_run_id'], ['check_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_run_id'], ['check_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_check_id'), 'incidents', ['check_id'], unique=False)
    op.create_index(op.f('ix_incidents_correlation_id'), 'incidents', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_incidents_state'), 'incidents', ['state'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('check_run_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_run_id'], ['check_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.add_column('checks', sa.Column('origin', sa.String(), server_default='HUMAN', nullable=False))
    op.add_column('checks', sa.Column('derived_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('checks', sa.Column('derived_at_commit', sa.String(), nullable=True))
    op.add_column('checks', sa.Column('human_edited_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('incident_id', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('external_key', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('external_url', sa.Text(), nullable=True))
    op.alter_column('tickets', 'check_run_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('tickets_check_run_id_key'), 'tickets', type_='unique')
    op.create_unique_constraint('uq_tickets_incident_id', 'tickets', ['incident_id'])
    op.drop_constraint(op.f('tickets_check_run_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(
        'fk_tickets_check_run_id', 'tickets', 'check_runs', ['check_run_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_tickets_incident_id', 'tickets', 'incidents', ['incident_id'], ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###

    _backfill_incidents_from_tickets()


def _backfill_incidents_from_tickets() -> None:
    """Give every pre-existing ticket the incident it should always have had.

    Derived entirely from the ticket and the run it points at: the check from
    the run, the timestamps from the ticket, and the state from two facts -
    the ticket's own status, and whether the check has passed since.

    That second condition matters more than it looks. Without it every
    historical ticket restores as a live incident, and on a database with a
    few hundred of them the reporting agent's first tick opens on hundreds of
    fires that went out months ago. An incident whose check has since passed
    is over, whatever its ticket still says - so it restores as CLEARED.

    Tickets whose run has since been deleted are left unlinked rather than
    attached to an invented incident.
    """
    op.execute(
        sa.text(
            """
            INSERT INTO incidents (
                id, check_id, state, severity, title, summary,
                opened_at, last_seen_at, cleared_at,
                first_run_id, last_run_id,
                failure_count, consecutive_passes, escalation_count,
                triage_source
            )
            SELECT
                md5(random()::text || t.id),
                r.check_id,
                CASE WHEN t.status = 'DONE' OR later.passed THEN 'CLEARED' ELSE 'OPEN' END,
                t.priority,
                t.title,
                'Reconstructed from a ticket filed before incidents existed.',
                t.created_at,
                t.updated_at,
                CASE
                    WHEN t.status = 'DONE' OR later.passed THEN t.updated_at
                    ELSE NULL
                END,
                t.check_run_id,
                t.check_run_id,
                1, 0, 0,
                'rule'
            FROM tickets t
            JOIN check_runs r ON r.id = t.check_run_id
            CROSS JOIN LATERAL (
                -- Has this check passed at any point after the failure the
                -- ticket was filed for? If so the incident is over.
                SELECT EXISTS (
                    SELECT 1 FROM check_runs later
                    WHERE later.check_id = r.check_id
                      AND later.status = 'PASSED'
                      AND later.started_at > r.started_at
                ) AS passed
            ) later
            WHERE t.incident_id IS NULL
            """
        )
    )
    # Re-joined on the run rather than carried through the INSERT, because
    # Postgres gives no way to return both generated and source ids together.
    op.execute(
        sa.text(
            """
            UPDATE tickets t
            SET incident_id = i.id
            FROM incidents i
            WHERE t.incident_id IS NULL
              AND i.first_run_id = t.check_run_id
              AND i.title = t.title
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tickets whose incident has no run behind it cannot satisfy the restored
    # NOT NULL on check_run_id, and there is nothing to derive one from - so
    # they are dropped rather than silently repointed at the wrong run.
    op.execute(sa.text("DELETE FROM tickets WHERE check_run_id IS NULL"))
    op.drop_constraint('fk_tickets_incident_id', 'tickets', type_='foreignkey')
    op.drop_constraint('fk_tickets_check_run_id', 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_check_run_id_fkey'), 'tickets', 'check_runs', ['check_run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_tickets_incident_id', 'tickets', type_='unique')
    op.create_unique_constraint(op.f('tickets_check_run_id_key'), 'tickets', ['check_run_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tickets', 'check_run_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tickets', 'external_url')
    op.drop_column('tickets', 'external_key')
    op.drop_column('tickets', 'incident_id')
    op.drop_column('checks', 'human_edited_at')
    op.drop_column('checks', 'derived_at_commit')
    op.drop_column('checks', 'derived_from')
    op.drop_column('checks', 'origin')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incidents_state'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_correlation_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_check_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
