-- DPM_SRC_CRM.BRONZE - raw landing layer for CRM customer records.
-- Deployed via the Snowflake MCP server; kept here so changes are tracked in
-- git and the RCA agent can attribute schema/pipeline changes to a commit +
-- author (see src/server/rca).

CREATE SCHEMA IF NOT EXISTS DPM_SRC_CRM.BRONZE;

CREATE SEQUENCE IF NOT EXISTS DPM_SRC_CRM.BRONZE.SEQ_CUSTOMER_ID START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS DPM_SRC_CRM.BRONZE.CUSTOMERS_RAW (
  RECORD_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  RAW_PAYLOAD VARIANT,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Bronze: raw landed CRM customer records (append-only)';

CREATE STREAM IF NOT EXISTS DPM_SRC_CRM.BRONZE.CUSTOMERS_RAW_STREAM
  ON TABLE DPM_SRC_CRM.BRONZE.CUSTOMERS_RAW
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new rows landed in bronze CRM customers';

CREATE OR REPLACE TASK DPM_SRC_CRM.BRONZE.TASK_BRONZE_TO_SILVER_CUSTOMERS
  WAREHOUSE = DPM_PIPELINE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('DPM_SRC_CRM.BRONZE.CUSTOMERS_RAW_STREAM')
AS
MERGE INTO DPM_SRC_CRM.SILVER.CUSTOMERS tgt
USING (
  SELECT
    RAW_PAYLOAD:customer_id::NUMBER AS CUSTOMER_ID,
    RAW_PAYLOAD:full_name::STRING AS FULL_NAME,
    RAW_PAYLOAD:email::STRING AS EMAIL,
    RAW_PAYLOAD:signup_date::DATE AS SIGNUP_DATE
  FROM DPM_SRC_CRM.BRONZE.CUSTOMERS_RAW_STREAM
  WHERE METADATA$ACTION = 'INSERT'
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
  FULL_NAME = src.FULL_NAME, EMAIL = src.EMAIL, SIGNUP_DATE = src.SIGNUP_DATE, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, FULL_NAME, EMAIL, SIGNUP_DATE, UPDATED_AT)
  VALUES (src.CUSTOMER_ID, src.FULL_NAME, src.EMAIL, src.SIGNUP_DATE, CURRENT_TIMESTAMP());
