-- DPM_SRC_BILLING.BRONZE - raw landing layer for billing invoice records.

CREATE SCHEMA IF NOT EXISTS DPM_SRC_BILLING.BRONZE;

CREATE SEQUENCE IF NOT EXISTS DPM_SRC_BILLING.BRONZE.SEQ_INVOICE_ID START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS DPM_SRC_BILLING.BRONZE.INVOICES_RAW (
  RECORD_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  RAW_PAYLOAD VARIANT,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Bronze: raw landed billing invoice records (append-only)';

CREATE STREAM IF NOT EXISTS DPM_SRC_BILLING.BRONZE.INVOICES_RAW_STREAM
  ON TABLE DPM_SRC_BILLING.BRONZE.INVOICES_RAW
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new rows landed in bronze billing invoices';

CREATE OR REPLACE TASK DPM_SRC_BILLING.BRONZE.TASK_BRONZE_TO_SILVER_INVOICES
  WAREHOUSE = DPM_PIPELINE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('DPM_SRC_BILLING.BRONZE.INVOICES_RAW_STREAM')
AS
MERGE INTO DPM_SRC_BILLING.SILVER.INVOICES tgt
USING (
  SELECT
    RAW_PAYLOAD:invoice_id::NUMBER AS INVOICE_ID,
    RAW_PAYLOAD:customer_id::NUMBER AS CUSTOMER_ID,
    RAW_PAYLOAD:product_id::NUMBER AS PRODUCT_ID,
    RAW_PAYLOAD:amount::NUMBER(12,2) AS AMOUNT,
    RAW_PAYLOAD:status::STRING AS STATUS,
    RAW_PAYLOAD:invoice_date::DATE AS INVOICE_DATE
  FROM DPM_SRC_BILLING.BRONZE.INVOICES_RAW_STREAM
  WHERE METADATA$ACTION = 'INSERT'
) src
ON tgt.INVOICE_ID = src.INVOICE_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = src.CUSTOMER_ID, PRODUCT_ID = src.PRODUCT_ID, AMOUNT = src.AMOUNT, STATUS = src.STATUS, INVOICE_DATE = src.INVOICE_DATE, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (INVOICE_ID, CUSTOMER_ID, PRODUCT_ID, AMOUNT, STATUS, INVOICE_DATE, UPDATED_AT)
  VALUES (src.INVOICE_ID, src.CUSTOMER_ID, src.PRODUCT_ID, src.AMOUNT, src.STATUS, src.INVOICE_DATE, CURRENT_TIMESTAMP());
